# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               OMNIA Platform Documentation
tagline:             'OMNIA Platform Documentation'
description:         'The place for documentation of the OMNIA Platform, a low-code platform to develop business applications.'
url:                 https://numbersbelieve.github.io
baseurl:             'omnia3/'
paginate:            5

# About/contact
author:
  name:              NumbersBelieve
  url:               http://www.numbersbelieve.com
  email:             sales@numbersbelieve.com

# Custom vars
version:             1.0.0
